FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
    python3 \
    python3-pip
RUN pip3 install --upgrade pip \
    && pip3 install setuptools

# for flask web server
EXPOSE 8081

# set working directory
WORKDIR /app
COPY . .

# install required libraries
RUN pip3 install -r requirements.txt

# This is the runtime command for the container
CMD [ "python3", "app/app.py" ]
